name: Renovate
on:
  workflow_dispatch: {} # allows manual triggering of the workflow
  schedule:
    - cron: '0 4 * * *' # once a day at 4:00 AM
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@dd5302ec17783b2fc721b19ae7209b57b1587765 # v46.1.17
        with:
          configurationFile: renovate.json
           # RENOVATE TOKEN: https://github.com/renovatebot/github-action#token
           # must have write access to the repository to create PRs, Issues
           # and read access to all public repositories to fetch dependencies's
           # changelogs and versions
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: 'debug'
